spring:
  datasource:
    url: ${CART_DB_URL}
    username: ${CART_DB_USER}
    password: ${CART_DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT_CART}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
